---
- debug: var=hubot verbosity=1
  tags: vars

- name: Ensure reauired packages are present using apt
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - redis-server
    - git

- name: Make sure the current directory of the hubot is present
  become: yes
  file:
    path: "{{ hubot.installation_path }}/{{ hubot.name }}"
    state: directory
    mode: 0777
    owner: "{{ ansible_user_id }}"

- name: "Install hubot app"
  git:
    repo: "{{ hubot.repo.url }}"
    dest: "{{ hubot.installation_path }}/{{ hubot.name }}"
    version: "{{ hubot.repo.version | default('master') }}"
    update: yes
    accept_hostkey: true
  when: hubot.repo.url is defined and hubot.repo.url != None
  notify: restart hubot

- name: Install packages of Hubot
  npm:
    path: "{{ hubot.installation_path }}/{{ hubot.name }}"
    state: latest
  notify: restart hubot

- name: Add environment varaibles
  template:
    src: "hubot.conf.j2"
    dest: "{{ hubot.installation_path }}/{{ hubot.name }}/hubot.conf"
    mode: 0755
  notify:
    - restart hubot

- name: Install Start/Stop script
  become: yes
  template:
    src: hubot.j2
    dest: /etc/init.d/hubot
    mode: 0755
  notify:
    - restart hubot
    - start hubot
